In [89]:
import pandas as pd

# Load CSV file into a DataFrame
df = pd.read_csv('/content/CC.csv')

In [90]:
df

,Age,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,\t\t\t\t\t\t\t\t\t\t\t\t\tLoan,Sec,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,\t\t\t\t\t\t\t\t\t\t\t\t\tA/C,CD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,\t\t\t\t\t\t\t\t\t\t\t\t\tA/C,Online,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Age,Experience,Income,ZIP,family,CCAvg,Education,Mortgage,Personalloan,Seca/c,CDa/c,Onlinea/c,Card approved
4,27,42,101,914263,5,2,Advanced,424,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
969,37,2,176,952859,1,4.1,Graduate,631,0,0,0,1,0
970,59,12,37,920929,4,8.51,Undergraduate,319,1,0,0,0,0
971,29,27,140,946622,5,2.62,Graduate,51,0,0,0,0,0
972,49,16,56,953988,2,10.08,Advanced,345,1,0,0,0,0
973,53,15,41,940503,4,10.22,Undergraduate,578,0,0,0,1,1

In [91]:
# Drop first three columns
df = df.iloc[3:, :]
df

,Age,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
3,Age,Experience,Income,ZIP,family,CCAvg,Education,Mortgage,Personalloan,Seca/c,CDa/c,Onlinea/c,Card approved
4,27,42,101,914263,5,2,Advanced,424,0,0,0,0,1
5,58,0,205,941189,4,0.06,Undergraduate,582,0,0,0,1,0
6,42,0,137,998163,5,9.87,Graduate,238,0,0,0,1,0
7,34,26,75,989968,5,8.27,Undergraduate,25,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
969,37,2,176,952859,1,4.1,Graduate,631,0,0,0,1,0
970,59,12,37,920929,4,8.51,Undergraduate,319,1,0,0,0,0
971,29,27,140,946622,5,2.62,Graduate,51,0,0,0,0,0
972,49,16,56,953988,2,10.08,Advanced,345,1,0,0,0,0
973,53,15,41,940503,4,10.22,Undergraduate,578,0,0,0,1,1

In [92]:
# Reset the index
df.reset_index(drop=True, inplace=True)
# Set the first row as the header
df.columns = df.iloc[0]

# Drop the first row after setting it as the header
df = df.iloc[1:]

# Reset the index
df.reset_index(drop=True, inplace=True)

df

,Age,Experience,Income,ZIP,family,CCAvg,Education,Mortgage,Personalloan,Seca/c,CDa/c,Onlinea/c,Card approved
0,27,42,101,914263,5,2,Advanced,424,0,0,0,0,1
1,58,0,205,941189,4,0.06,Undergraduate,582,0,0,0,1,0
2,42,0,137,998163,5,9.87,Graduate,238,0,0,0,1,0
3,34,26,75,989968,5,8.27,Undergraduate,25,0,0,0,0,1
4,28,29,57,938916,2,7.5,Advanced,369,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
965,37,2,176,952859,1,4.1,Graduate,631,0,0,0,1,0
966,59,12,37,920929,4,8.51,Undergraduate,319,1,0,0,0,0
967,29,27,140,946622,5,2.62,Graduate,51,0,0,0,0,0
968,49,16,56,953988,2,10.08,Advanced,345,1,0,0,0,0
969,53,15,41,940503,4,10.22,Undergraduate,578,0,0,0,1,1

In [96]:
df.isna().sum()

0
Age              0
Experience       0
Income           0
ZIP              0
family           0
CCAvg            0
Education        0
Mortgage         0
Personalloan     0
Seca/c           0
CDa/c            0
Onlinea/c        0
Card approved    0
dtype: int64

In [111]:
df.columns
if 'Card approved' in df.columns:
  print('t')

t

In [ ]:
from sklearn.preprocessing import MinMaxScaler

In [144]:
from sklearn.preprocessing import LabelEncoder, MinMaxScaler

def preprocess(df):
    # Change the data types of specific columns
    df['Age'] = df['Age'].astype(int)
    df['Experience'] = df['Experience'].astype(int)
    df['Income'] = df['Income'].astype(int)
    df['ZIP'] = df['ZIP'].astype(int)
    df['family'] = df['family'].astype(int)
    df['CCAvg'] = df['CCAvg'].astype(float)  # Change to float
    df['Mortgage'] = df['Mortgage'].astype(int)
    df['Personalloan'] = df['Personalloan'].astype(int)
    df['Seca/c'] = df['Seca/c'].astype(int)
    df['CDa/c'] = df['CDa/c'].astype(int)
    df['Onlinea/c'] = df['Onlinea/c'].astype(int)

    if 'Card approved' in df.columns:
        df['Card approved'] = df['Card approved'].astype(int)

    # Initialize LabelEncoder
    label_encoder = LabelEncoder()

    # Fit and transform the 'Education' column
    df['Education'] = label_encoder.fit_transform(df['Education'])

    # Initialize MinMaxScaler
    scaler = MinMaxScaler()

    # Normalize all columns
    df[df.columns] = scaler.fit_transform(df[df.columns])

    return df

In [ ]:
preprocess(df)

In [99]:
df

,Age,Experience,Income,ZIP,family,CCAvg,Education,Mortgage,Personalloan,Seca/c,CDa/c,Onlinea/c,Card approved
0,27,42,101,914263,5,2.00,0,424,0,0,0,0,1
1,58,0,205,941189,4,0.06,2,582,0,0,0,1,0
2,42,0,137,998163,5,9.87,1,238,0,0,0,1,0
3,34,26,75,989968,5,8.27,2,25,0,0,0,0,1
4,28,29,57,938916,2,7.50,0,369,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
965,37,2,176,952859,1,4.10,1,631,0,0,0,1,0
966,59,12,37,920929,4,8.51,2,319,1,0,0,0,0
967,29,27,140,946622,5,2.62,1,51,0,0,0,0,0
968,49,16,56,953988,2,10.08,0,345,1,0,0,0,0
969,53,15,41,940503,4,10.22,2,578,0,0,0,1,1

In [100]:
df.columns

Index(['Age', 'Experience', 'Income', 'ZIP', 'family', 'CCAvg', 'Education',
       'Mortgage', 'Personalloan', 'Seca/c', 'CDa/c', 'Onlinea/c',
       'Card approved'],
      dtype='object', name=0)

In [101]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 970 entries, 0 to 969
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Age            970 non-null    int64
 1   Experience     970 non-null    int64
 2   Income         970 non-null    int64
 3   ZIP            970 non-null    int64
 4   family         970 non-null    int64
 5   CCAvg          970 non-null    float64
 6   Education      970 non-null    int64
 7   Mortgage       970 non-null    int64
 8   Personalloan   970 non-null    int64
 9   Seca/c         970 non-null    int64
 10  CDa/c          970 non-null    int64
 11  Onlinea/c      970 non-null    int64
 12  Card approved  970 non-null    int64
dtypes: float64(1), int64(12)
memory usage: 98.6 KB

In [104]:
df_normalized

,Age,Experience,Income,ZIP,family,CCAvg,Education,Mortgage,Personalloan,Seca/c,CDa/c,Onlinea/c,Card approved
0,0.085106,0.933333,0.428571,0.142328,1.00,0.180328,0.0,0.671949,0.0,0.0,0.0,0.0,1.0
1,0.744681,0.000000,0.907834,0.411849,0.75,0.003643,1.0,0.922345,0.0,0.0,0.0,1.0,0.0
2,0.404255,0.000000,0.594470,0.982143,1.00,0.897086,0.5,0.377179,0.0,0.0,0.0,1.0,0.0
3,0.234043,0.577778,0.308756,0.900113,1.00,0.751366,1.0,0.039620,0.0,0.0,0.0,0.0,1.0
4,0.106383,0.644444,0.225806,0.389097,0.25,0.681239,0.0,0.584786,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
965,0.297872,0.044444,0.774194,0.528663,0.00,0.371585,0.5,1.000000,0.0,0.0,0.0,1.0,0.0
966,0.765957,0.266667,0.133641,0.209053,0.75,0.773224,1.0,0.505547,1.0,0.0,0.0,0.0,0.0
967,0.127660,0.600000,0.608295,0.466232,1.00,0.236794,0.5,0.080824,0.0,0.0,0.0,0.0,0.0
968,0.553191,0.355556,0.221198,0.539964,0.25,0.916211,0.0,0.546751,1.0,0.0,0.0,0.0,0.0
969,0.638298,0.333333,0.152074,0.404983,0.75,0.928962,1.0,0.916006,0.0,0.0,0.0,1.0,1.0

In [105]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

# Split the data into features (X) and the target variable (y)
X = df_normalized.drop('Card approved', axis=1)
y = df_normalized['Card approved']

# Split the data into training and testing sets (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=42)

# Initialize the Random Forest classifier
clf = RandomForestClassifier()

# Fit the classifier to the training data
clf.fit(X_train, y_train)

# Evaluate the classifier on the testing data
accuracy = clf.score(X_test, y_test)
print("Model accuracy:", accuracy)

Model accuracy: 0.7319587628865979

In [135]:
test_data = pd.read_csv("/content/1.csv")

In [137]:
test_data

,Age,Experience,Income,ZIP,family,CCAvg,Education,Mortgage,Personalloan,Seca/c,CDa/c,Onlinea/c
0,64,13,9,903510,1,2,Graduate,348,0,1,0,0
1,23,37,81,944453,2,1,Graduate,463,0,1,0,1
2,33,36,100,906091,1,4,Undergraduate,376,0,0,0,1
3,23,33,208,918716,5,7,Graduate,331,0,0,0,0
4,57,22,141,956653,3,10,Advanced,257,0,0,0,0
5,68,20,139,971775,2,1,Undergraduate,317,0,0,1,0
6,68,4,116,964914,5,8,Advanced,231,0,0,0,0
7,25,34,54,992966,4,0,Advanced,63,0,1,0,0
8,61,27,178,951077,3,6,Undergraduate,617,0,0,0,0
9,34,7,31,919733,1,5,Advanced,343,0,1,0,1

In [145]:
# Apply the preprocess function to your test data
preprocessed_test_data = preprocess(test_data)

In [146]:
preprocessed_test_data

,Age,Experience,Income,ZIP,family,CCAvg,Education,Mortgage,Personalloan,Seca/c,CDa/c,Onlinea/c
0,0.911111,0.272727,0.000000,0.000000,0.00,0.2,0.5,0.514440,0.0,1.0,0.0,0.0
1,0.000000,1.000000,0.361809,0.457689,0.25,0.1,0.5,0.722022,0.0,1.0,0.0,1.0
2,0.222222,0.969697,0.457286,0.028852,0.00,0.4,1.0,0.564982,0.0,0.0,0.0,1.0
3,0.000000,0.878788,1.000000,0.169983,1.00,0.7,0.5,0.483755,0.0,0.0,0.0,0.0
4,0.755556,0.545455,0.663317,0.594069,0.50,1.0,0.0,0.350181,0.0,0.0,0.0,0.0
5,1.000000,0.484848,0.653266,0.763113,0.25,0.1,1.0,0.458484,0.0,0.0,1.0,0.0
6,1.000000,0.000000,0.537688,0.686416,1.00,0.8,0.0,0.303249,0.0,0.0,0.0,0.0
7,0.044444,0.909091,0.226131,1.000000,0.75,0.0,0.0,0.000000,0.0,1.0,0.0,0.0
8,0.844444,0.696970,0.849246,0.531736,0.50,0.6,1.0,1.000000,0.0,0.0,0.0,0.0
9,0.244444,0.090909,0.110553,0.181352,0.00,0.5,0.0,0.505415,0.0,1.0,0.0,1.0

In [149]:
pred = clf.predict(preprocessed_test_data)

In [150]:
pred

array([1., 0., 0., 0., 0., 0., 0., 0., 0., 1.])